export const lgas = [
  "Abak",
  "Eastern Obolo",
  "Eket",
  "Esit Eket",
  "Essien Udim",
  "Etim Ekpo",
  "Etinan",
  "Ibeno",
  "Ibesikpo Asutan",
  "Ibiono-Ibom",
  "Ikot Abasi",
  "Ika",
  "Ikono",
  "Ikot Ekpene",
  "Ini",
  "Mkpat-Enin",
  "Itu",
  "Mbo",
  "Nsit-Atai",
  "Nsit-Ibom",
  "Nsit-Ubium",
  "Obot Akara",
  "Okobo",
  "Onna",
  "Oron",
  "Udung-Uko",
  "Ukanafun",
  "Oruk Anam",
  "Uruan",
  "Urue-Offong/Oruko",
  "Uyo",
];

export const schoolsArr = [
  {
    name: "Uyo High School",
    lga: lgas[30],
    description: "lorem pasum",
    avatar: null,
  },
  {
    name: "West Itam Secondary School",
    lga: lgas[30],
    description: "lorem pasum",
    avatar: null,
  },
];
